#!/usr/bin/env python3
"""Independent arithmetic reference model for finite C=1 local-mask systems.

Standard-library only.  It deliberately does not import repository verifier code.
"""
from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from hashlib import sha256
from math import gcd, lcm
from typing import Iterable, Sequence


@dataclass(frozen=True)
class OddRow:
    p: int
    K: int
    r: int
    E: tuple[int, ...]
    name: str = ""

    def __post_init__(self) -> None:
        if self.p <= 2 or self.p == 5:
            raise ValueError("odd row prime must be odd and different from 5")
        if self.K < 2:
            raise ValueError("K must be at least 2")
        if not self.E:
            raise ValueError("E must be nonempty")
        if any(v <= 0 or v >= self.K or v % 2 == 0 for v in self.E):
            raise ValueError("E must contain positive odd valuations below K")


@dataclass(frozen=True)
class TwoAdicRow:
    K: int
    r: int
    name: str = ""

    def __post_init__(self) -> None:
        if self.K < 2:
            raise ValueError("K_2 must be at least 2")


def factorint(n: int) -> dict[int, int]:
    if n < 1:
        raise ValueError("factorint expects a positive integer")
    out: dict[int, int] = {}
    while n % 2 == 0:
        out[2] = out.get(2, 0) + 1
        n //= 2
    d = 3
    while d * d <= n:
        while n % d == 0:
            out[d] = out.get(d, 0) + 1
            n //= d
        d += 2
    if n > 1:
        out[n] = out.get(n, 0) + 1
    return out


def multiplicative_order_prime(a: int, p: int) -> int:
    if gcd(a, p) != 1:
        raise ValueError("a and p must be coprime")
    order = p - 1
    for q in factorint(p - 1):
        while order % q == 0 and pow(a, order // q, p) == 1:
            order //= q
    return order


def valuation_nonzero(n: int, p: int) -> int:
    if n == 0:
        raise ValueError("valuation_nonzero does not define v_p(0)")
    v = 0
    while n % p == 0:
        n //= p
        v += 1
    return v


def lifting_exponent(p: int, w: int, cap: int = 12) -> int:
    """Return s=v_p(5^w-1), with a defensive finite cap."""
    s = 1
    if pow(5, w, p) != 1:
        raise ValueError("w is not an order multiple")
    while s < cap and pow(5, w, p ** (s + 1)) == 1:
        s += 1
    if s == cap and pow(5, w, p ** (cap + 1)) == 1:
        raise RuntimeError("lifting exponent exceeded defensive cap")
    return s


def odd_row_data(row: OddRow) -> dict[str, int]:
    w = multiplicative_order_prime(5, row.p)
    s = lifting_exponent(row.p, w)
    a = max(0, row.K - s)
    ell = w * (row.p ** a)
    return {"w": w, "s": s, "a": a, "ell": ell}


def odd_status_from_power(row: OddRow, anchor: int, power5: int) -> tuple[str, int | None]:
    mod = row.p ** row.K
    remainder = (row.r - pow(3, anchor, mod) - power5) % mod
    if remainder == 0:
        return "zero", None
    v = valuation_nonzero(remainder, row.p)
    if v in row.E:
        return "fatal", v
    return "safe", v


def odd_status(row: OddRow, anchor: int, d: int) -> tuple[str, int | None]:
    mod = row.p ** row.K
    return odd_status_from_power(row, anchor, pow(5, d, mod))


def odd_fatal(row: OddRow, anchor: int, d: int) -> bool:
    return odd_status(row, anchor, d)[0] == "fatal"


@lru_cache(maxsize=None)
def square_sum_residues_power_two(K: int) -> frozenset[int]:
    mod = 2 ** K
    squares = {x * x % mod for x in range(mod)}
    return frozenset((a + b) % mod for a in squares for b in squares)


def two_adic_unsafe(row: TwoAdicRow, anchor: int, d: int) -> bool:
    mod = 2 ** row.K
    remainder = (row.r - pow(3, anchor, mod) - pow(5, d, mod)) % mod
    return remainder not in square_sum_residues_power_two(row.K)


def two_adic_period(row: TwoAdicRow | None) -> int:
    if row is None or row.K == 2:
        return 1
    return 2 ** (row.K - 2)


def system_period(rows: Sequence[OddRow], two_row: TwoAdicRow | None = None) -> int:
    periods = [odd_row_data(row)["ell"] for row in rows]
    periods.append(two_adic_period(two_row))
    return lcm(*periods) if periods else 1


def coarse_period(rows: Sequence[OddRow], two_row: TwoAdicRow | None = None) -> int:
    periods = [odd_row_data(row)["w"] for row in rows]
    periods.append(two_adic_period(two_row))
    return lcm(*periods) if periods else 1


def row_status_vector(row: OddRow, anchor: int, period: int) -> bytearray:
    """0=safe, 1=fatal, 2=local zero; generated by recurrence."""
    mod = row.p ** row.K
    p5 = 1
    out = bytearray(period)
    for d in range(period):
        status, _ = odd_status_from_power(row, anchor, p5)
        out[d] = 1 if status == "fatal" else (2 if status == "zero" else 0)
        p5 = (p5 * 5) % mod
    return out


def direct_system_evaluation(
    rows: Sequence[OddRow],
    anchor: int,
    two_row: TwoAdicRow | None = None,
    period: int | None = None,
) -> dict[str, object]:
    L = period if period is not None else system_period(rows, two_row)
    row_vectors = [row_status_vector(row, anchor, L) for row in rows]
    witness_codes = bytearray(L)
    counts: dict[str, int] = {row.name or f"p={row.p}": 0 for row in rows}
    if two_row is not None:
        counts[two_row.name or "two_adic"] = 0
    safe_count = 0
    first_safe: int | None = None
    local_zero_counts = {row.name or f"p={row.p}": vec.count(2) for row, vec in zip(rows, row_vectors)}
    for d in range(L):
        witness = None
        for i, (row, vec) in enumerate(zip(rows, row_vectors), start=1):
            if vec[d] == 1:
                witness = row.name or f"p={row.p}"
                witness_codes[d] = i
                break
        if witness is None and two_row is not None and two_adic_unsafe(two_row, anchor, d):
            witness = two_row.name or "two_adic"
            witness_codes[d] = len(rows) + 1
        if witness is None:
            safe_count += 1
            if first_safe is None:
                first_safe = d
        else:
            counts[witness] += 1
    return {
        "period": L,
        "safe_count": safe_count,
        "covered_count": L - safe_count,
        "first_safe": first_safe,
        "first_witness_counts": counts,
        "local_zero_counts": local_zero_counts,
        "witness_sha256": sha256(bytes(witness_codes)).hexdigest(),
    }


def first_witness_on_progression(
    rows: Sequence[OddRow], anchor: int, modulus: int, residue: int, period: int
) -> dict[str, object]:
    if period % modulus != 0:
        raise ValueError("progression modulus must divide period")
    names = [row.name or f"p={row.p}" for row in rows]
    counts = {name: 0 for name in names}
    counts["safe"] = 0
    codes = bytearray()
    points: list[int] = []
    for d in range(residue % modulus, period, modulus):
        points.append(d)
        code = 0
        for i, row in enumerate(rows, start=1):
            if odd_fatal(row, anchor, d):
                counts[names[i - 1]] += 1
                code = i
                break
        if code == 0:
            counts["safe"] += 1
        codes.append(code)
    return {
        "modulus": modulus,
        "residue": residue % modulus,
        "point_count": len(points),
        "first_witness_counts": counts,
        "witness_sha256": sha256(bytes(codes)).hexdigest(),
    }


def coarse_fatal_by_enumeration(row: OddRow, anchor: int, x: int, U: int, L: int) -> bool:
    if L % U != 0:
        raise ValueError("U must divide L")
    statuses = [odd_status(row, anchor, x + U * k)[0] for k in range(L // U)]
    return bool(statuses) and all(status == "fatal" for status in statuses)


def corrupted_coarse_fatal_zero_as_last_shell(
    row: OddRow, anchor: int, x: int, U: int, L: int
) -> bool:
    """Deliberately wrong comparator: maps local zero to valuation K-1."""
    if L % U != 0:
        raise ValueError("U must divide L")
    accepted = set(row.E)
    for k in range(L // U):
        status, v = odd_status(row, anchor, x + U * k)
        if status == "zero":
            v = row.K - 1
        if v not in accepted:
            return False
    return True


def fraction_pair(numerator: int, denominator: int) -> list[int]:
    g = gcd(numerator, denominator)
    return [numerator // g, denominator // g]
